### ISSUE TITLE
[Feature Request] Better secret management

### ISSUE THREAD

**Issue by xyntechx** [aiverify-foundation/moonshot-data#105]
When defining our custom connector endpoints, the API key we input is stored as raw text in the JSON files. It is true that JSON doesn't have a concept of env vars, but I think it is important to not expose such sensitive data as raw text in these files, especially when people may want to create and push their own moonshot instance to remote repos :)

**Comment by imda-xinyitan** [comment]
Thank you for the feedback, this is useful! We have taken this up as a feature request and are working on it. (:

**Comment by imda-normanchia** [comment]
hello @xyntechx , currently you are able to use env vars to pass in your API key. All you need to do is 1. leave the token value blank in your endpoint. 2. put in the key in the environment variable. 

The key to put in the environment is dependent on the connector that you are planning to use.  An example for OpenAI connector is `export OPENAI_TOKEN=your_token_here` and for together connector is  `export TOGETHER_API_KEY=your_token_here`. 

The Environment Variable key to use is from the connector hence if you are using a different connector, you would need to find out what is the environment key that you are using. Do let me know if you have any issue with this. If not I would be closing the issue in a few days.

**Comment by xyntechx** [comment]
Awesome, thanks!
