### ISSUE TITLE
Encoding issues for non-English language in JSON results

### ISSUE THREAD

**Issue by imda-lseokmin** [aiverify-foundation/moonshot-data#55]
Currently, Moonshot stores unicode for non-English language in the json results (See below).

![image](https://github.com/aiverify-foundation/moonshot-data/assets/92433521/46461888-1c06-4c86-a3bb-cdaf7f13752b)

To reproduce this, run the following recipe and check the results in `generated-outputs/my-new-recipe-runner.json`.

```
run_recipe "my new recipe runner" "['cbbq-lite']" "['openai-gpt35-turbo']" -n 1 -r 1
```

**Comment by imda-lionelteo** [comment]
Hi @imda-lseokmin 
@imda-kelvinkok will be taking a look at this enhancement.

**Comment by imda-kelvinkok** [comment]
Hello, enhancement has been added in https://github.com/aiverify-foundation/moonshot-data/pull/56.

Closing this issue
